<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>Rwl.RhinoVerifier</AssemblyName>
    <RootNamespace>Rwl.RhinoVerifier</RootNamespace>
    <TargetExt>.rhp</TargetExt>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="RhinoCommon" Version="8.32.26160.13001" ExcludeAssets="runtime" PrivateAssets="all" />
    <Reference Include="System.Runtime.Serialization" />
  </ItemGroup>
</Project>
