<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>Rwl.RhinoVerifier</AssemblyName>
    <RootNamespace>Rwl.RhinoVerifier</RootNamespace>
    <TargetExt>.rhp</TargetExt>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="RhinoCommon">
      <HintPath>$(ProgramFiles)\Rhino 8\System\RhinoCommon.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="System.Runtime.Serialization" />
  </ItemGroup>
</Project>
